### ISSUE TITLE
Creative ideas

### ISSUE THREAD

**Issue by CheeseBurger2k** [TriangularEgg/edgequest#13]
perhaps add a rare item that allows you to tame a monster. Add a level system to the monsters and make it so the item only works on a monster that is less than yours. Or add a new skill that you can level up to make monsters your allies when you use a spell.

**Comment by CheeseBurger2k** [comment]
Also, nuke is t-sided

**Comment by TriangularEgg** [comment]
Cool

**Comment by TriangularEgg** [comment]
Taming monsters and monsters leveling is beyond the scope of this project at the moment, but I like the idea and will consider adding it as the project reaches completion. Reopen this issue in the future, thanks.
